### ISSUE TITLE
Genie errors out when dashboard contains a $ sign

### ISSUE THREAD

**Issue by hhaensel** [GenieFramework/StippleUI.jl#18] opened 2021-03-05 13:55 UTC
As soon as the text in the dashboard contains a $ sign, Genie reports an error
```
julia> ┌ Error: UndefVarError(:st__dashboard)
└ @ Genie.AppServer C:\Users\m136270\.julia\dev\Genie\src\AppServer.jl:185
┌ Error: UndefVarError: st__dashboard not defined
```
The underlying reason is that `Genie.Renderer.Html.html()`
treats data with $-sign differently (line 442):

```
  if occursin(raw"$", data) || occursin("<%", data) || layout !== nothing || forceparse
    Genie.Renderer.WebRenderable(Genie.Renderer.render(MIME"text/html", data; context = context, layout = layout, vars...), status, headers) |> Genie.Renderer.respond
  else
    Genie.Renderer.WebRenderable(body = data, status = status, headers = headers) |> Genie.Renderer.respond
  end
```
This also prevents inserting any js code that calls the intrinsic vue-function `$watch()`

I don't understand why this distinction is made, it probably has to do with Gumbo. Anyhow, the problem arises from the `parsehtml()` which inserts `st__dashboard()` which is not known to `Genie.Renderer.Html`.

@essenciary can you help here?

**Comment by essenciary** [comment] 2021-03-05 16:29
The `$` sign is used for Julia string interpolation. 

Is `$watch` inserted by the user? If not, can we escape it `\$watch`? Or can we replace it before rendering by using something like `_dollar_watch`?

**Comment by hhaensel** [comment] 2021-03-05 16:43
It also happens if $ appears in the regular text. It is not due to string interpoplation.

The problem is line 442 of `Html.jl`. If I eliminate the `occursin(raw"$", data) || ` from the condition, everything displays fine.

```
# Genie_3176175078122257035 

function func_e9e060c15315f2d2b8223ff90e5b27d33c1ece78() 


Genie.Renderer.Html.doctype() * 
Genie.Renderer.Html.html() do;[
	Genie.Renderer.Html.head() do;[
					Genie.Renderer.Html.link(href="https://fonts.googleapis.com/css?family=Material+Icons" , rel="stylesheet" )
		Genie.Renderer.Html.link(href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;0,900;1,400&display=swap" , rel="stylesheet" )
		Genie.Renderer.Html.link(href="/css/stipple/stipplecore.min.css" , rel="stylesheet" )
		Genie.Renderer.Html.link(href="/css/stipple/quasar.min.css" , rel="stylesheet" )	]end

	Genie.Renderer.Html.body() do;[
										Genie.Renderer.Html.div(id="HHDashboard" ) do;[
			st__dashboard() do;[
													Genie.Renderer.Html.header(class=" st-header q-pa-sm" ) do;[
					Genie.Renderer.Html.h1(class="st-header__title text-h3" ) do;[
						"""Stipple x-y Line Plot"""					]end
				]end
```

**Comment by essenciary** [comment] 2021-03-05 16:51
`$` is by design used for Julia code interpolation. So it's expected to be a valid expression in the line of `$(...julia here...)` or `$var` which is outputted as Julia code. Maybe you stumbled onto a bug, but potentially your $ expression can not be parsed as Julia.

**Comment by essenciary** [comment] 2021-03-05 16:56
This allows to generate dynamic output, like for example: 
```julia
span("Today is $(Dates.today())")
```

**Comment by essenciary** [comment] 2021-03-05 17:01
This has been a bit of a known issue, for example when using `$` for jQuery vars inside `script` tags. I'm not sure how to address it. 

We could have a flag which disables `$` parsing... but it doesn't sound like a good idea to globally disable it. Or have some sort of `rawjs` which makes that content a `raw` string.

**Comment by essenciary** [comment] 2021-03-05 17:25
@hhaensel Escaping seems OK: 

```julia
julia> using Genie.Renderer.Html

julia> using Dates

julia> span("Today is $(today())")
"<span>Today is 2021-03-05</span>"

julia> span("pay me $")
ERROR: syntax: invalid interpolation syntax: "$""
Stacktrace:
 [1] top-level scope
   @ none:1

julia> span("pay me \$")
"<span>pay me \$</span>"
```

**Comment by essenciary** [comment] 2021-03-05 17:26
@hhaensel Escaping seems OK: 

```julia
julia> using Genie.Renderer.Html

julia> using Dates

julia> span("Today is $(today())")
"<span>Today is 2021-03-05</span>"

julia> span("pay me $")
ERROR: syntax: invalid interpolation syntax: "$""
Stacktrace:
 [1] top-level scope
   @ none:1

julia> span("pay me \$")
"<span>pay me \$</span>"
```

But maybe you can provide an example of your test case and error, it might be different.

**Comment by essenciary** [comment] 2021-03-05 17:28
I think this is more like the issue (in the `Html` renderer): 

![image](https://user-images.githubusercontent.com/11292378/110151302-9c199280-7de0-11eb-8ab5-fe5557ed2f59.png)

**Comment by essenciary** [comment] 2021-03-05 17:31
It would need to be escaped 2 levels deep: 

```julia
julia> view = "<span>Hello, today is \\\$ pay day</span>"
"<span>Hello, today is \\\$ pay day</span>"

julia> html(view)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html><html><head></head><body><span>Hello, today is $ pay day</span></body></html>"""
```

**Comment by hhaensel** [comment] 2021-03-05 17:51
Put this in a dashboard and you will see the error. My MWE is
```
using Revise
using Stipple, StippleUI

Base.@kwdef mutable struct HHDashboard <: ReactiveModel
    name::R{String} = "World"
    a::R{Float64} = 1.0
    d::R{Any} = Dict()
end

model = Stipple.init(HHDashboard())

function ui(user)
    output = dashboard(root(model), class="container", [
        heading("Stipple x-y Line Plot"),
        row(
            cell(class="st-module", [h2(["Hello \\\$", span("", @text(:name)), "!"]), p("I am $user")])
        ),
        row(cell(class="st-module", [
            h5("What is your name?"),
            textfield("", :name, placeholder="type your name", label="Name", outlined="", filled="")
        ])),
        # make a nice bottom section
        row("&nbsp;")
    ], title = "Stipple x-y ApexChart" ) |> html
end

route("/") do
    # identify user from the header
  headers = Genie.Requests.getheaders()
  user = headers["User-Agent"] |> split |> last
  # deliver a user-spcific ui
  ui(user)
end

up(open_browser = true)

```

**Comment by essenciary** [comment] 2021-03-05 20:17
Thanks! 

Looks like a weird bug: 

```julia
julia> span("uuu \\\$") |> html
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html><html><head></head><body><span>uuu $</span></body></html>"""

julia> dashboard("uuu \\\$") |> html
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html><html><head></head><body></body></html>"""

julia> dashboard("uuu ") |> html
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<template><st-dashboard>uuu </st-dashboard></template>"""
```

**Comment by essenciary** [comment] 2021-03-05 20:20
Smallest MWE: 

```julia
julia> str = "<template><st-dashboard>uuu \\\$</st-dashboard></template>"
"<template><st-dashboard>uuu \\\$</st-dashboard></template>"

julia> html(str)
HTTP.Messages.Response:
"""
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8

<!DOCTYPE html><html><head></head><body></body></html>"""
```

**Comment by essenciary** [comment] 2021-03-05 21:15
@hhaensel I need to dig into this. The issue has to do with scopes (where are the various modules loaded, and when the code is parsed due to `$`, that affects the availability of the loaded modules). 

You can see this by running the example code and passing the `context = @__MODULE__` in `html`: 

```julia
function ui(user)
    output = dashboard(root(model), 
    [

        row(
            cell(class="st-module", [h2(["Hello \\\$", span("", @text(:name)), "!"]), p("I am $user")])
        )

        row(cell(class="st-module", [
            h5("What is your name?"),
            textfield("", :name, placeholder="type your name", label="Name", outlined="", filled="")
        ]))

    ], class="container", title = "Stipple x-y ApexChart")

    html(output, context = @__MODULE__)
end
```

---

However, I also found a new issue which might be related to the generation of the Vue code (and is present in both the $ and non-$ versions): 

![image](https://user-images.githubusercontent.com/11292378/110174341-4c4ac380-7e00-11eb-8ed8-e51e5a09e994.png)

This causes the page to render incorrectly.

**Comment by essenciary** [comment] 2021-03-05 21:59
Also, charts rendering broke between Stipple 0.7 and 0.8 - eg German Credits demo doesn't work anymore. 

![image](https://user-images.githubusercontent.com/11292378/110178237-6f787180-7e06-11eb-9e5c-6eb22fd30949.png)

Probably related to https://github.com/GenieFramework/Stipple.jl/issues/33

**Comment by essenciary** [comment] 2021-03-05 23:44
I fixed the invalid escape sequence (not pushed yet). Still looking into the unregistered components.

**Comment by essenciary** [comment] 2021-03-06 20:01
@hhaensel I opened an issue, maybe you have the chance to take a look into the "Unknown custom element error" - potentially related to the JS changes introduced in v0.8

**Comment by essenciary** [comment] 2021-03-11 08:27
@hhaensel Can we close this?

**Closed** 2021-03-11 22:24 UTC
